server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Fallback to index.html for Single Page Applications (Flutter Web)
    location / {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        try_files $uri $uri/ /index.html;
    }

    # Only cache media assets (images/fonts), not logic (js/html)

    # Only cache media assets (images/fonts), not logic (js/html)
    location ~* \.(?:ico|gif|jpe?g|png|woff2?|eot|ttf|svg|map)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}
